### ISSUE TITLE
SyntaxError in "trans.py" in python3

### ISSUE THREAD

**Issue by NewVadim** [zzzsochi/trans#15]
$ pip install trans
Collecting trans
  Using cached trans-2.0.1.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-hb_r_f/trans/setup.py", line 5, in <module>
        import trans
      File "trans.py", line 24
        """
          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hb_r_f/trans

error -> u'

**Comment by zzzsochi** [comment]
```bash

 $ python --version
Python 3.4.2
 $ pip install trans
Collecting trans
  Downloading trans-2.0.1.tar.bz2
Installing collected packages: trans
  Running setup.py install for trans
Successfully installed trans-2.0.1
```

**Comment by zzzsochi** [comment]
https://github.com/zzzsochi/trans/blob/master/setup.py#L27-L31
